In [7]:
import numpy as np

arr =  np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr[:, 1, np.newaxis]

array([[2],
       [5],
       [8]])

In [12]:
arr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [13]:
arr[:, [0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [15]:
arr[[1,2], [1, 2]]

array([5, 9])

In [20]:
# Boolean Indexing

arr[[[True, True, False], [True, True, False],[True, True, False]]]

array([1, 2, 4, 5, 7, 8])

In [34]:
# Sorting

arr = np.array([
    [1,7,5],
    [2,3,9],
    [8,4,6]
])

np.sort(arr.flatten()).reshape(arr.shape)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])